name: dsync_meetup_app
description: "A meetup app for social events and community building"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  collection: ^1.18.0
  flutter_animate: ^4.3.0

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.5
  provider: ^6.1.1

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.6
  firebase_analytics: ^11.4.6
  firebase_dynamic_links: ^6.1.7
  firebase_crashlytics: ^4.0.18
  firebase_performance: ^0.10.1+7
  google_maps_flutter: ^2.6.0
  geolocator: ^14.0.1
  firebase_remote_config: ^5.4.5

  # Authentication
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^6.0.4
  sign_in_with_apple: ^7.0.1

  # Routing
  go_router: ^15.2.0
  auto_route: ^10.1.0

  # Networking
  dio: ^5.4.0
  http: ^1.2.1 # Downgraded for compatibility

  # Media
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  video_player: ^2.10.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: 
  chewie: ^1.11.3

  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Notifications
  flutter_local_notifications: ^19.2.1
  flutter_native_timezone: ^2.0.0

  # Utilities
  uuid: ^4.0.0
  flutter_dotenv: ^5.1.0
  date_format: ^2.0.7
  url_launcher: ^6.3.0

  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0
  connectivity_plus: ^6.1.4

  # UI Components
  flutter_svg: ^2.0.7

  shimmer: ^3.0.0
  badges: ^3.0.0
  flutter_slidable: ^3.0.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0

  # Testing
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  test: ^1.25.15
  analyzer: ^7.4.5

  # Assets Generation
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/images/
    - lib/assets/animations/
    - lib/assets/fonts/
    - lib/core/localization/en.json
    - lib/core/localization/hi.json
    - lib/assets/onboarding/avatar1.jpg
    - lib/assets/onboarding/avatar2.jpg
    - lib/assets/onboarding/avatar3.jpg
    - lib/assets/onboarding/avatar4.jpg
    - lib/assets/onboarding/avatar5.jpg
    - lib/assets/onboarding/avatar6.jpg
    - lib/assets/onboarding/avatar7.jpg
    - lib/assets/onboarding/avatar8.jpg
    - lib/assets/onboarding/avatar9.jpg
    - lib/assets/onboarding/avatar10.jpg
    - lib/assets/onboarding/avatar11.jpg
    - lib/assets/onboarding/avatar12.jpg
    - lib/assets/onboarding/avatar13.jpg
    - lib/assets/onboarding/avatar14.jpg
    - lib/assets/onboarding/avatar15.jpg



    # - .env

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: lib/assets/fonts/Inter-Regular.ttf
  #       - asset: lib/assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: lib/assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: lib/assets/fonts/Inter-Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "lib/assets/images/splash_logo.png"
  android: true
  ios: true
  web: true


dependency_overrides:
  flutter_native_timezone:
    path: local/flutter_native_timezone-2.0.0



