name: flutter_native_timezone
description: A Flutter plugin for getting the local timezone of the OS.
version: 2.0.0
homepage: https://github.com/pinkfish/flutter_native_timezone

environment:
  sdk: ">=2.17.0 <4.0.0"     # ✅ Use newer SDK range (esp. for Dart 3 compatibility)
  flutter: ">=2.10.0"        # ✅ Match Flutter plugin v2 minimum

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ">=0.6.3 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.whelksoft.flutter_native_timezone
        pluginClass: FlutterNativeTimezonePlugin
      ios:
        pluginClass: FlutterNativeTimezonePlugin
      macos:
        pluginClass: FlutterNativeTimezonePlugin
      web:
        pluginClass: FlutterNativeTimezonePlugin
        fileName: flutter_native_timezone_web.dart
